In [50]:
import os
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

movies_train_data = pd.read_csv('../korea_movies_box_off_num/movies_train.csv')
movies_test_data = pd.read_csv('../korea_movies_box_off_num/movies_test.csv')
submission_data = pd.read_csv('../korea_movies_box_off_num/submission.csv')
movies_train_data.head(10)

,title,distributor,genre,release_time,time,screening_rat,director,dir_prev_bfnum,dir_prev_num,num_staff,num_actor,box_off_num
0,개들의 전쟁,롯데엔터테인먼트,액션,2012-11-22,96,청소년 관람불가,조병옥,0.00,0,91,2,23398
1,내부자들,(주)쇼박스,느와르,2015-11-19,130,청소년 관람불가,우민호,1161602.50,2,387,3,7072501
2,은밀하게 위대하게,(주)쇼박스,액션,2013-06-05,123,15세 관람가,장철수,220775.25,4,343,4,6959083
3,나는 공무원이다,(주)NEW,코미디,2012-07-12,101,전체 관람가,구자홍,23894.00,2,20,6,217866
4,불량남녀,쇼박스(주)미디어플렉스,코미디,2010-11-04,108,15세 관람가,신근호,1.00,1,251,2,483387
5,강철대오 : 구국의 철가방,롯데엔터테인먼트,코미디,2012-10-25,113,15세 관람가,육상효,837969.00,2,262,4,233211
6,길위에서,백두대간,다큐멘터리,2013-05-23,104,전체 관람가,이창재,0.00,0,32,5,53526
7,회사원,(주)쇼박스,액션,2012-10-11,96,청소년 관람불가,임상윤,739522.00,3,342,2,1110523
8,"1789, 바스티유의 연인들",유니버설픽쳐스인터내셔널코리아,뮤지컬,2014-09-18,129,전체 관람가,정성복,0.00,0,3,5,4778
9,청춘그루브,(주)두타연,드라마,2012-03-15,94,15세 관람가,변성현,0.00,0,138,3,868

In [51]:
movies_train_data['genre']=movies_train_data['genre'].map({'드라마':1,'멜로/로맨스':2,'다큐멘터리':3,'코미디':4})
movies_test_data['genre']=movies_test_data['genre'].map({'드라마':1,'멜로/로맨스':2,'다큐멘터리':3,'코미디':4})

In [52]:
movies_train_data['screening_rat']=movies_train_data['screening_rat'].map({'청소년 관람불가':0,'12세 관람가':1,'15세 관람가':2,'전체 관람가':3})
movies_test_data['screening_rat']=movies_test_data['screening_rat'].map({'청소년 관람불가':0,'12세 관람가':1,'15세 관람가':2,'전체 관람가':3})

In [53]:
X=movies_train_data[['genre', 'time', 'screening_rat', 'dir_prev_bfnum', 'dir_prev_num', 'num_staff', 'num_actor']]
y=movies_train_data['box_off_num']

X_test=movies_test_data[['genre', 'time', 'screening_rat', 'dir_prev_bfnum', 'dir_prev_num', 'num_staff', 'num_actor']]

X = X.fillna(-1)
X_test = X_test.fillna(-1)

In [54]:
from sklearn.ensemble import RandomForestRegressor
clf = RandomForestRegressor(random_state=0)

In [55]:
clf=clf.fit(X,y)

C:\Users\Kim han Chang\Anaconda3\envs\RL_Keras\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

In [56]:
movies_test_data['box_off_num']=clf.predict(X_test)

In [57]:
movies_test_data[['title','box_off_num']].to_csv("submission_baseline.csv",index=False)